[YUNIKORN-2993] Use empty array when `stateLog` not exists for `AppInfo`
When `stateLog` does not exist for some application returned by API `/ws/v1/partition/${partitionName}/queue/${queueName}/applications`, calling `appInfo.setLastStateChangeTime()` would trigger the following error:

```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at wne.setLastStateChangeTime (main.ec6040d2f2dbf6bb.js:1:775934)
```

We should fall back to empty array for `AppInfo.stateLog` when it doesn't exist in the API response.